xmind8: Update to 3.7.9
brave-simpletons/scoop-the-business pull request #155
Opened 2024-03-16 22:21 UTC by alexchapar

## What type of Apps related PR is this? (check all applicable)
- [ ] ✨ Add Manifest
- [ ] ♻️ Refactor
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 🚩 Other
## Description
Fix the manifest since the domain domain name changed
Update the version to the real number
## Related Tickets & Documents
Fixes #94
## [optional] What gif/emoji best describes this PR or how it makes you feel?
:alien: 🛸
## Did you verify the followings
### Add/Modify a description in the manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed
### Check URLs?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed
### Update to the latest version?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed
### Update Hashes?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed
### Format the json manifest?
- [x] 👍 yes
- [ ] 🙋 yes, but I need help
- [ ] 🙅 no, because they aren't needed
## Did you identify extra steps
### Notes in the manifest?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed
### Application Dependencies?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed
### Application Suggestions?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed
### Pre-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed
### Post-installation steps to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed
### File persistence to perform?
- [ ] 👍 yes
- [ ] 🙋 yes, but I need help
- [x] 🙅 no, because they aren't needed

2024-03-16 22:22 UTC, BotServiceAutomation commented
All changes look good.

Wait for review from human collaborators.
### xmind8

- [x] Description
- [x] License
- [x] Hashes
- [x] Checkver
- [x] Autoupdate

2024-03-17 02:02 UTC, Bibz87 requested changes

2024-03-17 02:02 UTC, Bibz87 commented on bucket/xmind8.json
> +        "url": "https://xmind.net/terms/"
```suggestion
        "url": "https://xmind.app/terms/"
```

2024-03-17 02:27 UTC, alexchapar commented on bucket/xmind8.json
> +        "url": "https://xmind.net/terms/"
Nice catch ! 😅

2024-03-18 00:58 UTC, Bibz87 approved these changes

2024-03-18 01:01 UTC, merged